### ISSUE TITLE
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

### ISSUE THREAD

**Issue by Allen-Zhou729** [gradio-app/gradio#10850]
### Describe the bug

Hi, I am using the latest version of Gradio.

But I encounter this problem:

![Image](https://github.com/user-attachments/assets/d672fd36-3686-4866-9056-f2d61cae15f2)

Do you know how can I solve this problem?  Thank you very much!

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python

import gradio as gr
gr.Interface(lambda x: x, "text", "text").launch(share=True)

```

### Logs

```shell

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.22.0
gradio_client version: 1.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.9.0
audioop-lts is not installed.
fastapi: 0.115.11
ffmpy: 0.5.0
gradio-client==1.8.0 is not installed.
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 0.29.3
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 1.24.4
orjson: 3.10.15
packaging: 24.2
pandas: 2.2.3
pillow: 11.0.0
pydantic: 2.10.6
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.11.1
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.46.1
tomlkit: 0.13.2
typer: 0.15.2
typing-extensions: 4.12.2
urllib3: 2.3.0
uvicorn: 0.34.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.28.1
huggingface-hub: 0.29.3
packaging: 24.2
typing-extensions: 4.12.2
websockets: 14.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Should be fixed now sorry about that!

**Comment by Allen-Zhou729** [comment]
> Should be fixed now sorry about that!

<img width="354" alt="Image" src="https://github.com/user-attachments/assets/36605de0-47b7-49c0-80c7-051567aa084c" />

It seems it hasn't been fixed. Is there some problem on my side?

**Comment by abidlabs** [comment]
Hmm can you test in reproductible environment like a Google Colab notebook?

**Comment by Allen-Zhou729** [comment]
> Hmm can you test in reproductible environment like a Google Colab notebook?

Hi, it seems no problem when I use Google Colab:

![Image](https://github.com/user-attachments/assets/1e8b7df2-7819-42fe-9321-00ae45c37a0a)

A very strange problem. My Internet connection is good, and I have already deactivated Firewall in my Ubuntu, but I am still having this problem even with a new, pure python env with only the newest version gradio installed.

**Comment by Allen-Zhou729** [comment]
I think I know why, my campus network doesn't support this kind of connection. My personal hotspot doesn't have this problem....

**Comment by abidlabs** [comment]
Can you tell us more about the campus network? Wondering if we can do anything about it or at least document this limitation

**Comment by zmxxmz0713** [comment]
You might download a wrong-version frpc_linux_amd64,just check it.
I hope this works for you.
