### ISSUE TITLE
More detailed feedback with flagging

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#118]
One issue I've heard from academic users is the ability to pass in more detailed feedback with flagging. I can imagine for example, when the flagging button is clicked, for a dropdown to happen below it, which includes some or all of the following:

* a thumbs up / thumbs down button to clarify if the prediction is correct / incorrect
* a textbox that allows freeform input
* ability to modify the prediction itself (e.g. for an image output ability to edit it --> though this would probably be a lot of work since it would be interface-dependent)

**Comment by piraka9011** [comment]
On this note, can you improve the way you store audio feedback when flagged?
Instead of the base64 string of audio file in the csv, can it be a file, and the csv contains the file name?

**Comment by aliabd** [comment]
Thanks for ..flagging.. this @piraka9011, we'll definitely implement it.

**Comment by aliabd** [comment]
@piraka9011 this is fixed in https://github.com/gradio-app/gradio/commit/00ef4e47d02dbd690e613ad950e5bd9cc5248592

We'll include it in the next pip update. You can go ahead and install from github to use it. Please let us know if you have any issues or feedback.

**Comment by piraka9011** [comment]
I'll give it a shot now, thanks!

**Comment by piraka9011** [comment]
Just wanted to confirm this is working but was wondering why the base64 file is still in the CSV?
I think it just clutters the CSV (My 2c)

**Comment by aliabid94** [comment]
Can you confirm you’re using gradio >1.6? Files are stored in folders now, not base64 representations

**Comment by piraka9011** [comment]
Indeed, they are stored in files, but the base64 encodings still show up in the CSV.

**Comment by aliabid94** [comment]
Hmm that shouldn’t be the behaviout, I’ll take a look

**Comment by aliabid94** [comment]
@piraka9011 I have not been able to reproduce on gradio = 1.6.1. Can you confirm your version number?

**Comment by piraka9011** [comment]
I had to refresh my virtualenv and it works. Thanks for the follow up!
Feel free to close @aliabid94
