### ISSUE TITLE
Gradio shared url throws error in UI  if response take more than 70 seconds.

### ISSUE THREAD

**Issue by alenma04** [gradio-app/gradio#140]

**Comment by stefanmijic** [comment]
I've run into the same issue. I'm using Gradio as a training interface, that requires more then half an hour to generate the output. I've so far only been able to circumvent the issue. The operation does finish usually and everything is visible from the console, though the UI only shows an error (after approximately a minute or so after initiating it).

**Comment by aliabid94** [comment]
Currently this is an issue when running Gradio in Colab, or when share=True. Working on a fix.

**Comment by aliabid94** [comment]
This is now fixed - new timeout is 10 minutes. Thanks for pointing this out!

**Comment by aliabid94** [comment]
Brought up the timeout to one hour.

**Comment by stefanmijic** [comment]
Is the issue fixed in the current 1.6.4 release? I just tried running the code and still had a timeout error after a few minutes (both running it locally as well as via Gradio with share=True).

**Comment by aliabid94** [comment]
Gradio version shouldn't matter, the timeout happens at the external server. Did it timeout around 5 minutes? I realized I hadn't updated one config, changed it from 5 min to 1 hour just now, can you try again?

**Comment by stefanmijic** [comment]
I still get the same timeout error after about 5 minutes. This is also the case for different scripts, that also take a rather long time to execute.

**Comment by aliabid94** [comment]
Alright I'll take a look.

**Comment by NikitaJangid22** [comment]
I'm facing the run time error issue, the time that my code requires to output is 30 mins.

> Alright I'll take a look.

I'm facing the run time error issue, the time that my code requires to output is 30 mins.

**Comment by abidlabs** [comment]
Closing due to staleness. If this is still an issue, please reopen.
