### ISSUE TITLE
Websocket connection fails inside browser console for hosted version

### ISSUE THREAD

**Issue by altryne** [gradio-app/gradio#2096]
### Describe the bug

I'm trying to add share=True and the interface gets a random *.gradio.app subdomain which is great.

But then the interface doesn't seem to do anything, looking in the browser console it shows: 

```index.04cd3ffd.js:7833 WebSocket connection to 'wss://36624.gradio.app/queue/join' failed: 
```

![CleanShot 2022-08-26 at 18 03 44@2x](https://user-images.githubusercontent.com/463317/187005623-7c890d3f-0c9c-4c68-8a87-e9981ad2aa50.jpg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

added share=True to the launch() command

```
webui.queue()
webui.launch(share=True
```

### Screenshot

![CleanShot 2022-08-26 at 18 03 44@2x](https://user-images.githubusercontent.com/463317/187005662-1e36c405-3a5f-4cb7-a36f-e1f2accb105a.jpg)

### Logs

```shell
Logs don't show anything
```

### System Info

```shell
I tried this on both windows and mac, and this worked yesterday with the same code
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
@aliabid94 could this be related to any recent changes in the queue?

**Comment by abidlabs** [comment]
@altryne does this work fine if you don’t enable the queue?

**Comment by altryne** [comment]
@abidlabs Thank you for the fast reply, removing the queue indeed solves this in my example

**Comment by abidlabs** [comment]
Ok that helps, we’ll look into this!

**Comment by abidlabs** [comment]
This should be fixed now @altryne! Here's a colab that shows queuing + iterative outputs: https://colab.research.google.com/drive/1kBfWpPUAZ5EOvl9P4RR9EiqCT35urtQM?usp=sharing

**Comment by colemickens** [comment]
I'm sorry that I can't provide better debug info about this, and my lack of sureness is why I'm not opening a new issue yet... but...

I had a lot of websocket issues, even with 3.3.1 - bad enough that with sd-web-ui, it would hangup the entire backend, with subsequent attempts causing the queue to get bigger (from peeking at ws messages), with no signs of anything happening on the backend. (This could of course be an application bug)

However, these issues completely went away when switching to Firefox. I'm partly throwing this out there in case someone else is having a similar issue and doubting themselves. And maybe looking for some feedback - is Gradio commonly tested with Firefox?

**Comment by colemickens** [comment]
(I'll edit, but replying just in case) I made an important typo. My problems went away when switching *from Firefox* to Chrome.

**Comment by abidlabs** [comment]
Thanks @colemickens for letting us and the community know! We typically test on Chrome + Edge, so it's possible that there could be some Firefox-specific issues may have crept in. If you can share a minimal example that doesn't work on Firefox, feel free to create a new issue, and we can give that a look.

**Comment by songw** [comment]
question still exist!
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1639828/196640678-7625e273-4865-4477-85c8-993b105b00e7.png">

gradio's version is 3.5

**Comment by abidlabs** [comment]
Hi @songw can you please share more information about the code & the browser and OS that you are running on when you get this issue?

**Comment by songw** [comment]
detailed code is as follow：
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1639828/196832031-668be684-f341-4569-b64c-b9dc3820d1f1.png">

browser is chrome。

OS is linux。

if visit via ip+port, it’s ok。
if visit via hostname, it will generate above question.
