### ISSUE TITLE
Chatbot component does not show status tracker

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3914]
### Describe the bug

When running a chatbot demo, I noticed that the chatbot component does not display the queue status or progress information for a pending event.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Add a long sleep to the `chatbot_multimodal` demo

```python
import gradio as gr
import time

def add_text(history, text):
    history = history + [(text, None)]
    return history, ""

def add_file(history, file):
    history = history + [((file.name,), None)]
    return history

def bot(history):
    time.sleep(10)
    response = "**That's cool!**"
    history[-1][1] = response
    return history

with gr.Blocks() as demo:
    chatbot = gr.Chatbot([], elem_id="chatbot").style(height=750)
    
    with gr.Row():
        with gr.Column(scale=0.85):
            txt = gr.Textbox(
                show_label=False,
                placeholder="Enter text and press enter, or upload an image",
            ).style(container=False)
        with gr.Column(scale=0.15, min_width=0):
            btn = gr.UploadButton("📁", file_types=["image", "video", "audio"])
            
    txt.submit(add_text, [chatbot, txt], [chatbot, txt]).then(
        bot, chatbot, chatbot
    )
    btn.upload(add_file, [chatbot, btn], [chatbot]).then(
        bot, chatbot, chatbot
    )

if __name__ == "__main__":
    demo.launch()
```

Then launch with queueing with `SYSTEM=spaces python demo/chatbot_multimodal/run.py`

Open up two tabs and send a message at around the same time. 

The textbox component shows the queue information:

<img width="1136" alt="Screen Shot 2023-04-19 at 3 07 07 PM" src="https://user-images.githubusercontent.com/41651716/233175794-54467aa2-4299-4609-9163-9259cc5a6262.png">

But the chatbot does not:
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/41651716/233175761-338ebd44-031a-410c-abec-832ce493becb.png">

This is a problem because if the event handler did not return the textbox, the queue information would not be displayed to the user at all!

### Logs

```shell
-
```

### System Info

```shell
3.27.0
```

### Severity

serious, but I can work around it

**Comment by aliabid94** [comment]
We need to come up with a design of a subtler statustracker that doesn't cover up the component, other components would also benefit from being able to optionally have a subtler statustracker instead. For chatbot this could appear in the loading dots. For other components (and maybe chatbot as well), we could have this information tucked in a corner in "subtle status tracker" mode, like a component Label.

**Comment by freddyaboulton** [comment]
Since chatbot has no status tracker, the error modal will not be displayed if chatbot is the only output component of an event. I think this issue should fix that as well for the chatbot case but #3347 would also be a general fix.

**Comment by pseudotensor** [comment]
@freddyaboulton What's the work-around?

**Comment by freddyaboulton** [comment]
Hi @pseudotensor !

The workaround I mentioned is to additionally update a component that properly displays the status tracker. In this case, it's the textbox where users type the message. 

In my example above, `add_text` resets the textbox to be an empty string

```python
def add_text(history, text):
    history = history + [(text, None)]
    return history, ""
```

And the submit event on the textbox lists itself as output

```python
    txt.submit(add_text, [chatbot, txt], [chatbot, txt]).then(
        bot, chatbot, chatbot
    )
```

So then the textbox will display the status:

![image](https://user-images.githubusercontent.com/41651716/235691574-f1a1aefa-8fdc-41eb-ac81-f9be96872248.png)

**Comment by pseudotensor** [comment]
Hmm.  I tried this, and while it seems to work, it fails more generally.

Try 3+ tabs and puts a message into them at same time.  The others will show the correct queue position at first (e.g. 1/4, 2/4, 3/4, 4/4).

However, once the 2nd page gets going, the 3+ tabs suddenly just show the 3 dots again.  And so the other 2 pages not yet really going still show the 3 dots instead of queue.

Same thing happens with your code snippet, locally with queue enabled:

```
import gradio as gr
import time

def add_text(history, text):
    history = history + [(text, None)]
    return history, ""

def add_file(history, file):
    history = history + [((file.name,), None)]
    return history

def bot(history):
    time.sleep(10)
    response = "**That's cool!**"
    history[-1][1] = response
    return history

with gr.Blocks() as demo:
    chatbot = gr.Chatbot([], elem_id="chatbot").style(height=750)

    with gr.Row():
        with gr.Column(scale=0.85):
            txt = gr.Textbox(
                show_label=False,
                placeholder="Enter text and press enter, or upload an image",
            ).style(container=False)
        with gr.Column(scale=0.15, min_width=0):
            btn = gr.UploadButton("📁", file_types=["image", "video", "audio"])

    txt.submit(add_text, [chatbot, txt], [chatbot, txt]).then(
        bot, chatbot, chatbot
    )
    btn.upload(add_file, [chatbot, btn], [chatbot]).then(
        bot, chatbot, chatbot
    )

if __name__ == "__main__":
    demo.queue()
    demo.launch()
```

**Comment by abidlabs** [comment]
Given all the Chatbot demos, I feel like this is important enough we should add to 3.x milestone. The demos are basically unusable without an ETA / queue rank

**Comment by pseudotensor** [comment]
@abidlabs any status on this one?

For me, this issue is probably even more important than https://github.com/gradio-app/gradio/issues/4245 -- even though 4245 is pretty bad.
