### ISSUE TITLE
FileExplorer Directory Display

### ISSUE THREAD

**Issue by titafox** [gradio-app/gradio#6376]
### Describe the bug

I encountered some confusing behavior while using FileExplorer:

My directory structure is as follows:

- images
  - 0001
    - 000.jpg
    - 001.jpg
  - 0002
  - 000.jpg
    - red
      - 015.jpg
      - 016.jpg
    - green
      - 022.jpg
      - 023.jpg
  - 0003
    - yellow
      - 031.jpg
      - 032.jpg
    - orange
      - 045.jpg
      - 046.jpg

I have the following issues:

1. By default, with glob="**/*.*," I expected the frontend to display the directory structure as described above, but the actual display treats directories as files. When I add content to ignore_glob, such as ignore_glob="*.db," the directory structure displays correctly, but at the bottom, it shows the contents of directories as if they were files.

2. I tried using glob="*/*.*," and while the files display correctly, my subdirectories do not appear.

Currently, the only solution I've found is to inherit and rewrite the FileExplorer class to address this issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.FileExplorer(file_count="multiple", root="images", ignore_glob="*.db",
                    interactive=True, glob="**/*.*")

demo.launch()
```

- images
  - 0001
    - 000.jpg
    - 001.jpg
  - 0002
  - 000.jpg
    - red
      - 015.jpg
      - 016.jpg
    - green
      - 022.jpg
      - 023.jpg
  - 0003
    - yellow
      - 031.jpg
      - 032.jpg
    - orange
      - 045.jpg
      - 046.jpg

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.47.1
gradio_client version: 0.6.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.99.1
ffmpy: 0.3.1
gradio-client==0.6.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.3.4
numpy: 1.24.4
orjson: 3.9.7
packaging: 23.0
pandas: 2.0.2
pillow: 8.1.0
pydantic: 1.10.7
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 5.4.1
requests: 2.31.0
semantic-version: 2.8.5
typing-extensions: 4.7.1
uvicorn: 0.22.0
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 0.9.0
httpx: 0.24.1
huggingface-hub: 0.17.3
packaging: 23.0
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Interesting, thanks @titafox for the bug report, we'll look into it!

**Comment by abidlabs** [comment]
Hi @titafox @rrfaria this should be fixed now I believe.

Could you try installing `gradio` from this branch: 

```py
pip install https://gradio-builds.s3.amazonaws.com/97cd3139fa22d3616e80eeda30fce68cfb74239d/gradio-4.9.0-py3-none-any.whl
```

and see if you still observe this issue?

**Comment by rrfaria** [comment]
@abidlabs I installed but it is not working. I was using version 4.7.1 before install it. 

```sh
 import gradio._simple_templates
  File "myapp\venv\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>       
    from .simpledropdown import SimpleDropdown
  File "myapp\venv\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module> 
    from gradio.components.base import FormComponent
  File "myapp\venv\Lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "myapp\venv\Lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>      
    from gradio.components.base import Component
  File "myapp\venv\Lib\site-packages\gradio\components\base.py", line 21, in <module>
    from gradio.blocks import Block, BlockContext
  File "myapp\venv\Lib\site-packages\gradio\blocks.py", line 28, in <module>
    from gradio import (
  File "myapp\venv\Lib\site-packages\gradio\networking.py", line 20, in <module>
    from gradio.routes import App
  File "myapp\venv\Lib\site-packages\gradio\routes.py", line 45, in <module>
    from gradio_client.utils import ServerMessage
ImportError: cannot import name 'ServerMessage' from 'gradio_client.utils' (myapp\venv\Lib\site-packages\gradio_client\utils.py)
```

**Comment by rrfaria** [comment]
I upgrade to version 4.9.1 and now it works 
but on network tab you can see request `component_server/` taking too much time to resolve.
and filexplorer take too much time to show files. 

I even restarted the app but still the same.

I noticed entier app is very slow now.

**Comment by rrfaria** [comment]
I reverted to 4.7.1 and it works smooth but I need the fix present on 4.9.1. Is there any breaking change or any config I need to do on 4.9.1?

**Comment by abidlabs** [comment]
Hi @rrfaria can you share more details to help us reproduce this? Example code + the latencies you’re seeing on 4.7 vs 4.9 would be helpful

**Comment by freddyaboulton** [comment]
> ImportError: cannot import name 'ServerMessage' from 'gradio_client.utils'

@rrfaria You also need to install gradio client version 0.7.3!

**Comment by abidlabs** [comment]
I'm closing this issue for lack of activity. If you have a repro you can share @rrfaria we are happy to look into it some more.
