### ISSUE TITLE
Audio component: gradio RuntimeError: Response content shorter than Content-Length

### ISSUE THREAD

**Issue by JackismyShephard** [gradio-app/gradio#8878]
### Describe the bug

I am developing a gradio app with many instantiations of the `Audio` components (think 10+).  I have observed that `Audio` components serving as output for event listener functions load new audio (in my case represented using file paths) very slowly and in some cases will not be able to load the new audio at all. In these cases I am getting a `RuntimeError: Response content shorter than Content-Length` in my terminal. A similar issue has been reported before at https://github.com/gradio-app/gradio/issues/8351 and (partially) at https://github.com/gradio-app/gradio/issues/7155.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This is a bit hard at the moment as the relevant code is quite large and complex, but I can work on trying to reproduce the behaviour in a simple script if that is necessary.

### Screenshot

![image](https://github.com/user-attachments/assets/5f3b0f73-2fef-44d1-bfc9-2391b8ff8513)

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 534, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\Jacki\ai_audio\ultimate-rvc\dependencies\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 534, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
```

### System Info

```shell
Gradio 4.38.1

Python 3.11 (using miniconda)

Windows 11 (also tested on Ubuntu 22.04 and 24.04)
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @JackismyShephard yes a repro would be very helpful here!

**Comment by JackismyShephard** [comment]
@abidlabs So I have finally managed to write a small script that reproduces the error in one scenario: when downloading audio from youtube and trying to load this audio:

```python
import gradio as gr
import yt_dlp


def _yt_download(link: str) -> str:
    link = link.split("&")[0]
    outtmpl = "0_%(title)s_Original"
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
        "format": "bestaudio",
        "outtmpl": outtmpl,
        "ignoreerrors": True,
        "nocheckcertificate": True,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "wav",
                "preferredquality": 0,
            }
        ],
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        result = ydl.extract_info(link, download=True)
        download_path = ydl.prepare_filename(result, outtmpl=f"{outtmpl}.wav")

    return download_path


with gr.Blocks(title="Ultimate RVC") as app:

    audio_link = gr.Text(
        label="Song link",
    )
    audio_output = gr.Audio(label="audio output", type="filepath", interactive=False)
    audio_input = gr.Audio(label="audio_input", type="filepath")
    retrieve_audio_btn = gr.Button("Retrieve audio", variant="primary")

    retrieve_audio_btn.click(
        _yt_download,
        inputs=[audio_link],
        outputs=[audio_output],
    ).success(
        lambda v: gr.Audio(value=v),
        inputs=[audio_output],
        outputs=[audio_input],
    )


if __name__ == "__main__":
    app.launch()
```
The first time I try to load audio with this script, it is successful, but upon trying to load new audio, usually the second (and sometimes also the first) audio component do(es) not update. In this case the error seems to be due to chaining event listeners (the error also occurs when using the `.then` method).

**Comment by abidlabs** [comment]
thanks @JackismyShephard! let me cc @hannahblair who is looking into audio component bugs

**Comment by JackismyShephard** [comment]
@abidlabs @hannahblair Are there any updates on this issue?

**Comment by kmanninen** [comment]
Hi. I am also looking for a solution to this issue. I am experiencing it locally - running Gradio on Windows and Ubuntu. My use case involves users either recording audio or uploading their own .wav files.

Specifically, this bug occurs when I add example .wav files to the interface and users select examples to load. The examples are usually no longer than 2 minutes each. After the user selects two or three examples the Gradio UI becomes very sluggish uploading or recording any new audio files. A peek into the browser console log shows numerous pending calls to "upload". In my command line, where Gradio is running, I receive a "Response content shorter than Content-Length" error, similar to the original post of this issue.

**Comment by mauricio-fernandez-l** [comment]
Any update on this? I get the same error already with the minimal code

```python
import gradio as gr

with gr.Blocks() as demo:
    audio = gr.Audio(sources="microphone", type="filepath", scale=1)

demo.launch(inbrowser=True)
```

Errors are particularly likely to be triggered by short audio.

**Comment by dannyweng88122** [comment]
I am also get the same issue. Are there any updates?

**Comment by loglux** [comment]
I have the same question!!!
Some changes in the methods above the Gradio interface can affect the presence of this error. But I'm not 100% sure. The same piece of code and the same file can cause or not cause the issue  
```
   with gr.Row():
        audio_input = gr.Audio(type="filepath", label="Upload an audio file") 
```

**Comment by abidlabs** [comment]
I'm pretty sure this is the same as https://github.com/gradio-app/gradio/issues/9537 and should be fixed now in the latest version of gradio!

**Comment by mauricio-fernandez-l** [comment]
@abidlabs Sadly not, tested it just now in a fresh conda environment with gradio 5.38.0 and python 3.11.

```shell
(gr) C:\Users\mauri>pip show gradio
Name: gradio
Version: 5.38.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: https://github.com/gradio-app/gradio
Author:
Author-email: Abubakar Abid <gradio-team@huggingface.co>, Ali Abid <gradio-team@huggingface.co>, Ali Abdalla <gradio-team@huggingface.co>, Dawood Khan <gradio-team@huggingface.co>, Ahsen Khaliq <gradio-team@huggingface.co>, Pete Allen <gradio-team@huggingface.co>, Ömer Faruk Özdemir <gradio-team@huggingface.co>, Freddy A Boulton <gradio-team@huggingface.co>, Hannah Blair <gradio-team@huggingface.co>
License-Expression: Apache-2.0
Location: C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages
Requires: aiofiles, anyio, brotli, fastapi, ffmpy, gradio-client, groovy, httpx, huggingface-hub, jinja2, markupsafe, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, ruff, safehttpx, semantic-version, starlette, tomlkit, typer, typing-extensions, uvicorn
Required-by:

(gr) C:\Users\mauri>python
Python 3.11.13 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:03:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio as gr
>>>
>>> with gr.Blocks() as demo:
...     audio = gr.Audio(sources="microphone", type="filepath", scale=1)
...
>>> demo.launch(inbrowser=True)
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

>>> ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\gradio\brotli_middleware.py", line 74, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\gradio\route_utils.py", line 878, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\routing.py", line 76, in app
    await response(scope, receive, send)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\responses.py", line 369, in __call__
    await self._handle_simple(send, send_header_only, send_pathsend)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\responses.py", line 400, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 507, in send
    output = self.conn.send(event=h11.EndOfMessage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\h11\_connection.py", line 538, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\h11\_connection.py", line 571, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "C:\Users\mauri\miniconda3\envs\gr\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

**Comment by abidlabs** [comment]
Ok I'll reopen until we can take a closer look

**Comment by freddyaboulton** [comment]
@abidlabs fixed our conda package and I can't repro this locally when installing with pip so I will close but let us know if it's still an issue

**Comment by mauricio-fernandez-l** [comment]
Sorry to bother you @freddyaboulton , but it is still not solved. Just checked now, with fresh local venv and gradio 5.46.1. I just pressed record and immediately after that stop (you may have to try 5 consecutive times). It sometimes happens with short recordings.

main.py

```python
import gradio as gr

with gr.Blocks() as demo:
    audio = gr.Audio(sources="microphone")

demo.launch(inbrowser=True)
```

Console output

```shell
(venv) C:\Users\mauri\Downloads\gradio_audio>pip show gradio
Name: gradio
Version: 5.46.1
Summary: Python library for easily interacting with trained machine learning models
Home-page: https://github.com/gradio-app/gradio
Author: 
Author-email: Abubakar Abid <gradio-team@huggingface.co>, Ali Abid <gradio-team@huggingface.co>, Ali Abdalla <gradio-team@huggingface.co>, Dawood Khan <gradio-team@huggingface.co>, Ahsen Khaliq <gradio-team@huggingface.co>, Pete Allen <gradio-team@huggingface.co>, Ömer Faruk Özdemir <gradio-team@huggingface.co>, Freddy A Boulton <gradio-team@huggingface.co>, Hannah Blair <gradio-team@huggingface.co>
License-Expression: Apache-2.0
Location: C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages
Requires: aiofiles, anyio, audioop-lts, brotli, fastapi, ffmpy, gradio-client, groovy, httpx, huggingface-hub, jinja2, markupsafe, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, ruff, safehttpx, semantic-version, starlette, tomlkit, typer, typing-extensions, uvicorn
Required-by: 

(venv) C:\Users\mauri\Downloads\gradio_audio>python main.py
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\fastapi\applications.py", line 1082, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\gradio\brotli_middleware.py", line 74, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\gradio\route_utils.py", line 882, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await response(scope, receive, send)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\responses.py", line 369, in __call__
    await self._handle_simple(send, send_header_only, send_pathsend)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\responses.py", line 400, in _handle_simple
    await send({"type": "http.response.body", "body": chunk, "more_body": more_body})
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\_exception_handler.py", line 39, in sender
    await send(message)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 507, in send
    output = self.conn.send(event=h11.EndOfMessage())
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\h11\_connection.py", line 538, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\h11\_connection.py", line 571, in send_with_data_passthrough
    writer(event, data_list.append)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\Downloads\gradio_audio\venv\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

**Comment by Corginyan** [comment]
Same here https://github.com/gradio-app/gradio/issues/7490#issuecomment-5002604265
