### ISSUE TITLE
[Gradio 5] - Gallery with two "X" close button

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#9956]
### Describe the bug

I have noticed that the gallery in the latest version of Gradio is showing 2 buttons to close the gallery image, and the button on top is interfering with the selection of the buttons below. This happens when I am in preview mode, either starting in preview mode or after clicking on the image to preview.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks(analytics_enabled=False) as app:   
    gallery = gr.Gallery(label="Generated Images",  interactive=True, show_label=True, preview=True, allow_preview=True)

app.launch(inbrowser=True)

```

### Screenshot

![image](https://github.com/user-attachments/assets/f9824d58-4cd5-4206-a119-c863211eece1)

### Logs

```shell
N/A
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.5.0
gradio_client version: 1.4.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
audioop-lts is not installed.
fastapi: 0.115.4
ffmpy: 0.4.0
gradio-client==1.4.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.25.2
jinja2: 3.1.3
markupsafe: 2.1.5
numpy: 1.26.3
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.2.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.1
ruff: 0.5.6
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.41.2
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.5
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.25.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
This has been fixed on main @elismasilva !

**Comment by freddyaboulton** [comment]
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/97ff7906-7380-4a87-8182-8671871b4ae1">

**Comment by elismasilva** [comment]
@freddyaboulton ok i wait for next release because if i install from main i need do contribution guide steps, has any way  to install from main and run like is installed from pip? i getting error "ValueError: Did you install Gradio from source files? You need to build the frontend by running /scripts/build_frontend.sh" but i already run this script, so i will not wast time with this, this is a little bug.

**Comment by elismasilva** [comment]
> @elismasilva - you can go to the `Chore: Update Versions` PR and scroll to the `Install Gradio from this PR` comment. It has a link to a built wheel corresponding to the latest changes in the main branch. Right now it is:
> 
> ```
> pip install https://gradio-pypi-previews.s3.amazonaws.com/540dc498700aae5ef3adb943e3ebdaf0c97edc7c/gradio-5.5.0-py3-none-any.whl
> ```

hi @freddyaboulton , ive installed from this PR gradio client and gradio app, but the issue persists. Ive uninstalled previous versios, re-created new venv and have this:

![image](https://github.com/user-attachments/assets/189d18d4-8a8e-4252-89b4-63580ac2951f)

**Comment by freddyaboulton** [comment]
@elismasilva - can you share a full reproducer? I can't reproduce on spaces: https://huggingface.co/spaces/gradio/fake_gan

**Comment by elismasilva** [comment]
> @elismasilva - can you share a full reproducer? I can't reproduce on spaces: https://huggingface.co/spaces/gradio/fake_gan

Hi @freddyaboulton, I discovered that the problem only occurs if I use the gallery in interactive mode when it is used as an Image component allowing you to upload an image it seems that the behavior of the two components merge and generate this conflict. See in my space I enabled the option for you to be able to specify an image for the gallery, if you specify an image or click on the generated images the additional "X" will appear.

https://huggingface.co/spaces/elismasilva/fake_gan

in my reproduction code provided here in this issue you can se the problem too.
